### ISSUE TITLE
What's an easy way to get ONLY the new messages from MessageLoop?

### ISSUE THREAD

**Issue by federicotorrielli** [AmanoTeam/amanobot#18]
Hello,
Every time I start my bot it fetches all the messages from the telegram API queue. Is there a way to get only the messages from when the bot is started on? 
For now the code to start the bot looks like this:
```    
bot = amanobot.aio.DelegatorBot(TOKEN, [
pave_event_space()(
    per_chat_id(), create_open, MessageHandler, timeout=20),
])
loop = asyncio.get_event_loop()
loop.create_task(MessageLoop(bot).run_forever())
loop.run_forever()
```
And I would like to add an option to handle only the newest messages. Thanks in advance for the support!

**Comment by alissonlauffer** [comment]
> Is there a way to get only the messages from when the bot is started on

Sorry for the late response, but you can use a `bot.getUpdates(offset=-1)` at the second line to drop all old updates. See https://core.telegram.org/bots/api#getupdates.

But yeah, a parameter that does that automatically would be nice.
